export const countryStateData = {
    Afghanistan: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"],
    Albania: ["Tirana", "Durrës", "Shkodër", "Vlorë"],
    Algeria: ["Algiers", "Oran", "Constantine", "Annaba"],
    Andorra: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana"],
    Angola: ["Luanda", "Huambo", "Lobito", "Benguela"],
    Argentina: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza"],
    Armenia: ["Yerevan", "Gyumri", "Vagharshapat", "Vanadzor"],
    Australia: ["New South Wales", "Victoria", "Queensland", "Western Australia"],
    Austria: ["Vienna", "Graz", "Linz", "Salzburg"],
    Azerbaijan: ["Baku", "Ganja", "Sumqayit", "Lankaran"],
    Bahamas: ["Nassau", "Freeport", "West End", "Georgetown"],
    Bahrain: ["Manama", "Riffa", "Muharraq", "Sitra"],
    Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi"],
    Barbados: ["Bridgetown", "Speightstown", "Oistins", "Bathsheba"],
    Belarus: ["Minsk", "Gomel", "Mogilev", "Vitebsk"],
    Belgium: ["Brussels", "Antwerp", "Ghent", "Bruges"],
    Belize: ["Belmopan", "San Ignacio", "Corozal", "Belize City"],
    Benin: ["Porto-Novo", "Cotonou", "Djougou", "Parakou"],
    Bhutan: ["Thimphu", "Phuentsholing", "Punakha", "Paro"],
    Bolivia: ["Sucre", "La Paz", "Santa Cruz", "Cochabamba"],
    'Bosnia and Herzegovina': ["Sarajevo", "Banja Luka", "Tuzla", "Zenica"],
    Botswana: ["Gaborone", "Francistown", "Molepolole", "Maun"],
    Brazil: ["Brasília", "São Paulo", "Rio de Janeiro", "Salvador"],
    Brunei: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"],
    Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas"],
    'Burkina Faso': ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora"],
    Burundi: ["Gitega", "Bujumbura", "Ngozi", "Muramvya"],
    Cambodia: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
    Cameroon: ["Yaoundé", "Douala", "Garoua", "Bamenda"],
    Canada: ["Alberta", "British Columbia", "Ontario", "Quebec", "Manitoba"],
    'Cape Verde': ["Praia", "Mindelo", "Santa Maria", "São Filipe"],
    Chad: ["N'Djamena", "Moundou", "Sarh", "Abéché"],
    Chile: ["Santiago", "Valparaíso", "Concepción", "La Serena"],
    China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"],
    Colombia: ["Bogotá", "Medellín", "Cali", "Barranquilla"],
    Comoros: ["Moroni", "Moutsamoudou", "Domoni", "Moya"],
    Congo: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi"],
    'Costa Rica': ["San José", "Alajuela", "Cartago", "Heredia"],
    Croatia: ["Zagreb", "Split", "Rijeka", "Osijek"],
    Cuba: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín"],
    Cyprus: ["Nicosia", "Limassol", "Larnaca", "Famagusta"],
    'Czech Republic': ["Prague", "Brno", "Ostrava", "Plzeň"],
    Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
    Djibouti: ["Djibouti", "Ali Sabieh", "Tadjourah", "Dikhil"],
    Dominica: ["Roseau", "Portsmouth", "Salisbury", "Marigot"],
    'Dominican Republic': ["Santo Domingo", "Santiago", "La Romana", "Puerto Plata"],
    Ecuador: ["Quito", "Guayaquil", "Cuenca", "Machala"],
    Egypt: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh"],
    'El Salvador': ["San Salvador", "Santa Ana", "San Miguel", "Sonsonate"],
    Estonia: ["Tallinn", "Tartu", "Narva", "Kohtla-Järve"],
    Eswatini: ["Mbabane", "Manzini", "Siteki", "Piggs Peak"],
    Ethiopia: ["Addis Ababa", "Gondar", "Mekele", "Dire Dawa"],
    Fiji: ["Suva", "Nadi", "Lautoka", "Labasa"],
    Finland: ["Helsinki", "Espoo", "Vantaa", "Tampere"],
    France: ["Paris", "Marseille", "Lyon", "Toulouse"],
    Gabon: ["Libreville", "Port-Gentil", "Franceville", "Moanda"],
    Gambia: ["Banjul", "Serekunda", "Brikama", "Bakau"],
    Georgia: ["Tbilisi", "Kutaisi", "Batumi", "Zugdidi"],
    Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
    Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi"],
    Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
    Grenada: ["St. George's", "Grenville", "Sauteurs", "Carriacou"],
    Guatemala: ["Guatemala City", "Quetzaltenango", "Escuintla", "San Marcos"],
    Guinea: ["Conakry", "Kankan", "Nzérékoré", "Kindia"],
    Guyana: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina"],
    Haiti: ["Port-au-Prince", "Cap-Haïtien", "Les Cayes", "Jacmel"],
    Honduras: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"],
    Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc"],
    Iceland: ["Reykjavik", "Kopavogur", "Akureyri", "Selfoss"],
    India: ["Delhi", "Karnataka", "Maharashtra", "Tamil Nadu", "Uttar Pradesh"],
    Indonesia: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    Iran: ["Tehran", "Mashhad", "Isfahan", "Shiraz"],
    Iraq: ["Baghdad", "Basra", "Mosul", "Erbil"],
    Ireland: ["Dublin", "Cork", "Limerick", "Galway"],
    Israel: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon Lezion"],
    Italy: ["Rome", "Milan", "Naples", "Turin"],
    Jamaica: ["Kingston", "Montego Bay", "Mandeville", "Ocho Rios"],
    Japan: ["Tokyo", "Osaka", "Yokohama", "Nagoya"],
    Jordan: ["Amman", "Irbid", "Zarqa", "Aqaba"],
    Kazakhstan: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda"],
    Kenya: ["Nairobi", "Mombasa", "Kisumu", "Eldoret"],
    Kiribati: ["Tarawa", "Betio", "Bairiki", "Nikunau"],
    Kuwait: ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya"],
    Kyrgyzstan: ["Bishkek", "Osh", "Jalal-Abad", "Talas"],
    Laos: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet"],
    Latvia: ["Riga", "Daugavpils", "Liepaja", "Jelgava"],
    Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre"],
    Lesotho: ["Maseru", "Teyateyaneng", "Maputsoe", "Leribe"],
    Liberia: ["Monrovia", "Gbarnga", "Bong", "Buchanan"],
    Libya: ["Tripoli", "Benghazi", "Misrata", "Zliten"],
    Liechtenstein: ["Vaduz", "Schaan", "Balzers", "Eschen"],
    Lithuania: ["Vilnius", "Kaunas", "Klaipeda", "Šiauliai"],
    Luxembourg: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Ettelbruck"],
    Madagascar: ["Antananarivo", "Toamasina", "Antsiranana", "Mahajanga"],
    Malawi: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"],
    Malaysia: ["Kuala Lumpur", "George Town", "Johor Bahru", "Malacca"],
    Maldives: ["Malé", "Addu City", "Fuvahmulah", "Dhidhdhoo"],
    Mali: ["Bamako", "Sikasso", "Segou", "Koutiala"],
    Malta: ["Valletta", "Sliema", "Birkirkara", "Mosta"],
   ' Marshall Islands': ["Majuro", "Ebeye", "Laura", "Rongelap"],
    Mauritania: ["Nouakchott", "Nouadhibou", "Kaédi", "Selibaby"],
    Mauritius: ["Port Louis", "Beau Bassin", "Quatre Bornes", "Vacoas"],
    Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Puebla"],
    Micronesia: ["Palikir", "Kolonia", "Weno", "Madolenihmw"],
    Moldova: ["Chișinău", "Bălți", "Bender", "Rîbnița"],
    Monaco: ["Monaco", "Monte Carlo", "La Condamine", "Menton"],
    Mongolia: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"],
    Montenegro: ["Podgorica", "Nikšić", "Herceg Novi", "Bijelo Polje"],
    Morocco: ["Rabat", "Casablanca", "Marrakech", "Fes"],
    Mozambique: ["Maputo", "Beira", "Nampula", "Chimoio"],
    Myanmar: ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine"],
    Namibia: ["Windhoek", "Swakopmund", "Walvis Bay", "Oshakati"],
    Nepal: ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur"],
    Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
   ' New Zealand': ["Wellington", "Auckland", "Christchurch", "Hamilton"],
    Nicaragua: ["Managua", "León", "Granada", "Masaya"],
    Niger: ["Niamey", "Zinder", "Maradi", "Diffa"],
    Nigeria: ["Abuja", "Lagos", "Kano", "Port Harcourt"],
   ' North Korea': ["Pyongyang", "Hamhung", "Nampo", "Wonsan"],
    Norway: ["Oslo", "Bergen", "Stavanger", "Drammen"],
    Oman: ["Muscat", "Salalah", "Sohar", "Nizwa"],
    Pakistan: ["Islamabad", "Karachi", "Lahore", "Peshawar"],
    Palau: ["Ngerulmud", "Melekeok", "Koror", "Airai"],
    Panama: ["Panama City", "Colón", "David", "La Chorrera"],
 '   Papua New Guinea': ["Port Moresby", "Lae", "Mount Hagen", "Madang"],
    Paraguay: ["Asunción", "Ciudad del Este", "Luque", "Encarnación"],
    Peru: ["Lima", "Arequipa", "Cusco", "Trujillo"],
    Philippines: ["Manila", "Quezon City", "Cebu City", "Davao City"],
    Poland: ["Warsaw", "Kraków", "Wrocław", "Gdańsk"],
    Portugal: ["Lisbon", "Porto", "Braga", "Coimbra"],
    Qatar: ["Doha", "Al Rayyan", "Umm Salal", "Al Khor"],
    Romania: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
    Russia: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
    Rwanda: ["Kigali", "Butare", "Gisenyi", "Musanze"],
   ' Saint Kitts and Nevis': ["Basseterre", "Charlestown", "Nanny Cay", "Dieppe Bay Town"],
   ' Saint Lucia': ["Castries", "Soufrière", "Vieux Fort", "Gros Islet"],
   ' Saint Vincent and the Grenadines': ["Kingstown", "Argyle", "Bequia", "Union Island"],
    Samoa: ["Apia", "Mulifanua", "Salelologa", "Savaii"],
  '  San Marino': ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"],
  '  Saudi Arabia': ["Riyadh", "Jeddah", "Mecca", "Dammam"],
    Senegal: ["Dakar", "Touba", "Thiès", "Saint-Louis"],
    Serbia: ["Belgrade", "Novi Sad", "Niš", "Kragujevac"],
    Seychelles: ["Victoria", "Anse Royale", "Beau Vallon", "La Digue"],
   ' Sierra Leone': ["Freetown", "Bo", "Kenema", "Makeni"],
    Singapore: ["Singapore", "Jurong East", "Tampines", "Yishun"],
    Slovakia: ["Bratislava", "Košice", "Nitra", "Prešov"],
    Slovenia: ["Ljubljana", "Maribor", "Celje", "Kranj"],
    'Solomon Islands': ["Honiara", "Gizo", "Auki", "Lata"],
    Somalia: ["Mogadishu", "Hargeisa", "Kismayo", "Baidoa"],
    'South Africa': ["Pretoria", "Cape Town", "Durban", "Johannesburg"],
    'South Korea': ["Seoul", "Busan", "Incheon", "Daegu"],
   ' South Sudan': ["Juba", "Wau", "Malakal", "Bor"],
    Spain: ["Madrid", "Barcelona", "Valencia", "Sevilla"],
    'Sri Lanka': ["Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle"],
    Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Nyala"],
    Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
    Switzerland: ["Bern", "Zurich", "Geneva", "Lausanne"],
    Syria: ["Damascus", "Aleppo", "Homs", "Latakia"],
    Taiwan: ["Taipei", "Kaohsiung", "Taichung", "Tainan"],
    Tajikistan: ["Dushanbe", "Khujand", "Kulyab", "Istaravshan"],
    Tanzania: ["Dodoma", "Dar es Salaam", "Arusha", "Mwanza"],
    Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Nakhon Ratchasima"],
    Togo: ["Lomé", "Sokodé", "Kara", "Atakpamé"],
    Tonga: ["Nuku'alofa", "Ha'apai", "Vava'u", "Eua"],
   ' Trinidad and Tobago': ["Port of Spain", "San Fernando", "Scarborough", "Chaguanas"],
    Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan"],
    Turkey: ["Ankara", "Istanbul", "Izmir", "Antalya"],
    Turkmenistan: ["Ashgabat", "Turkmenabat", "Mary", "Dashoguz"],
    Tuvalu: ["Funafuti", "Vaiaku", "Nanumea", "Nukufetau"],
    Uganda: ["Kampala", "Entebbe", "Gulu", "Mbarara"],
    Ukraine: ["Kyiv", "Kharkiv", "Odesa", "Lviv"],
  '  United Arab Emirates': ["Abu Dhabi", "Dubai", "Sharjah", "Ajman"],
    'United Kingdom': ["London", "Birmingham", "Manchester", "Glasgow"],
    'United States': ["California", "Florida", "New York", "Texas", "Washington"],
    Uruguay: ["Montevideo", "Salto", "Paysandú", "Maldonado"],
    Uzbekistan: ["Tashkent", "Samarkand", "Bukhara", "Andijan"],
    Vanuatu: ["Port Vila", "Luganville", "Norsup", "Lenakel"],
    'Vatican City': ["Vatican City"],
    Venezuela: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"],
    Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong"],
    Yemen: ["Sana'a", "Aden", "Taiz", "Hudaida"],
    Zambia: ["Lusaka", "Ndola", "Kitwe", "Livingstone"],
    Zimbabwe: ["Harare", "Bulawayo", "Gweru", "Mutare"],
};
